apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  labels:
    app: server-pod
spec:
  containers:
  - name: server-pod
    image: tndyd5390/nonstop-server:0.1
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /liveness
        port: 8080
    readinessProbe:
      httpGet:
        path: /readiness
        port: 8080
 
